### ISSUE TITLE
Move Line Up, Move Line Down

### ISSUE THREAD

**Issue by rafattouqir** [kaunteya/Linex#2]
@kaunteya Hi, You've done great work, I was looking for the Move Line UP and Move Line DOWN features.

If you could add it in your extension, it would be great extensions

**Comment by kaunteya** [comment]
Hey. Thanks..
Move line up /down is already there in the Xcode

<img width="675" alt="screen shot 2017-10-04 at 11 31 37 am" src="https://user-images.githubusercontent.com/2352321/31161861-8fcdffc4-a8c9-11e7-8255-36f1ac585b1d.png">
