### ISSUE TITLE
Multiple cursors

### ISSUE THREAD

**Issue by Dschee** [kaunteya/Linex#3]
It would be great to have multiple cursors or a similar feature. The use case is:

- I have a bunch of code where the same thing repeats in many lines, for example:

```
let variableA: Double
let variableB: Double
let variableC: Double
let variableD: Double
let variableE: Double
```
- I might want to change ...
  - ... change the `let` to `var` for all of these lines OR
  - ... the type from `Double` to `Int` for all of these lines OR
  - ... the prefix `variable` to `store` for all of these lines
- To do this, I simply mark the part I want to change in the first line
- Then I type a short-cut, e.g. `Cmd+D` which marks the same text in the next line
- I retype the shortcut until I have marked all occurrences lines
- Then, when I start typing, all lines are changed simultaneously

This feature can be found in some text editors, like SublimeText or Atom. It would be great if we could get the benefits in Xcode as well. Currently I'm copying my code to Atom, change it there and recopy back to Xcode. Would be great not to have to do this.

**Comment by kaunteya** [comment]
@Dschee Its technically infeasible. Xcode does not allow plugins to create multiple cursors.
So you will have to continue jumping on Atom for this.

**Comment by Dschee** [comment]
As I already wrote, it's not only about having multiple cursors. It's about having the same advantages. I know you can't write multiple cursors via an extension. But maybe you can highlight multiple places and edit multiple parts of the file? That should be possible. I don't think you should close this without having thought this through. And I don't have the feeling you have.
